### ISSUE TITLE
RFD 444 refactoring

### ISSUE THREAD

**Issue by mkeeter** [oxidecomputer/crucible#1042]
We want to refactor the Crucible Upstairs to have fewer tasks and locks:
https://rfd.shared.oxide.computer/rfd/444#_counter_proposal_one_big_task

**Comment by leftwo** [comment]
https://github.com/oxidecomputer/crucible/pull/1058 Is in.

We may be able to close this issue now.

**Comment by mkeeter** [comment]
Yup, closing!
