### ISSUE TITLE
Add back DTrace probe for upstairs sending an IO to the downstairs

### ISSUE THREAD

**Issue by leftwo** [oxidecomputer/crucible#1273]
The `__io__start` probe family formerly did this (from the comment in
`upstairs/src/lib.rs`):
```
/// ds__*__io__start: This is when a downstairs task puts an IO on the
/// wire to the actual downstairs that will do the work. This probe has
/// both the job ID and the client ID so we can tell the individual
/// downstairs apart.
/// 
/// ds__*__io_done: An ACK has been received from a downstairs for an IO
/// sent to it. At the point of this probe the IO has just come off the
/// wire and we have not processed it yet.
```

This is no longer true, the probes now indicate when the upstairs sends
a message (the IO) to the task responsible for sending it over the wire. The 
done is after the IO is pulled off the wire and we are in post processing for 
that IO.

While these probe locations might be interesting, we really need back the
specific "on the wire" and "off the wire" points.

If the probe names themselves don't change and new probes are added, then
the comment around the probes should be updated to reflect what they
are actually recording.

**Comment by jclulow** [comment]
I think it would also be cool if we could record the packet send time with **Instant::now()** and calculate the delta in, say, microseconds, when we get the reply.  We could provide that latency to the **done** probe, and eventually presumably fold it into some oximeter metric stuff.
