### ISSUE TITLE
Add bulk export integration test(s)

### ISSUE THREAD

**Issue by jmpesp** [oxidecomputer/crucible#1346]
There's a bunch of bulk import integration tests, but no bulk export tests - add some!

**Comment by jmpesp** [comment]
I'm closing this, there actually are bulk read integration tests (test_pantry_bulk_read, test_pantry_bulk_read_max_chunk_size, test_pantry_validate, and more)

**Comment by leftwo** [comment]
What about the bulk export tests?

**Comment by jmpesp** [comment]
Sorry, to be clear: the term "bulk export" is synonymous with "bulk read", and we have tests that cover that operation. I had forgot about those when I opened this issue.
