### ISSUE TITLE
Move `structopt` to `clap`

### ISSUE THREAD

**Issue by leftwo** [oxidecomputer/crucible#190]
As of 3.0 clap, structop is now integrated.
Migrate all the structopt usage to clap. 
See the good work done by Steve in https://github.com/oxidecomputer/humility/commit/d79c0cb1b6091ac3a8e7df542c9fff2a0b677991
for inspiration.

**Comment by leftwo** [comment]
The model PR from Steve https://github.com/oxidecomputer/humility/pull/84/files

**Comment by leftwo** [comment]
Some parts are moved (client, cli, dsc).

**Comment by leftwo** [comment]
https://github.com/oxidecomputer/crucible/pull/348

**Comment by luqmana** [comment]
Fixed as of https://github.com/oxidecomputer/crucible/commit/579356c914103d145512ca79739bb8dfef768eba
