### ISSUE TITLE
Volume: what is the correct generation number to use?

### ISSUE THREAD

**Issue by jmpesp** [oxidecomputer/crucible#198]
Subvolumes may have different generation numbers, is there support for this? What generation number (if any) should the Volume use?

**Comment by leftwo** [comment]
The support for generation numbers also needs to exist on the Nexus side

**Comment by leftwo** [comment]
We figured this out, each subvolume has it's own generation number.
Read only parents don't need one, as they never change.
generation numbers are stored in Nexus
