### ISSUE TITLE
Why is `tools/test_up.sh` taking so long (~30 min) in the CI?

### ISSUE THREAD

**Issue by leftwo** [oxidecomputer/crucible#230]
Figure this out, make it faster, do what is write, not what is wrong.

**Comment by jclulow** [comment]
Does it take less time in some other environment?

**Comment by leftwo** [comment]
tools/test_up.sh may not be the issue here, just a piece.
It's really that `build-and-test.sh` takes ~30 minutes.  I think we can trim that down by:
both using pre-compiled binaries from a previous step.
Run the different sub-tests in `test_up.sh` in parallel, if we have the VM resources for it, assuming those don't take too long to spin up. 

Let me post some actual numbers for the `test_up.sh` on my machine and Atrium and see how they compare with what we get from github.

**Comment by leftwo** [comment]
Some data from Atrium.
The `build-and-test.sh` takes ~18 minutes when it has to compile everything (16 if already compiled)
cargo test is about half a second
`test_up.sh unencrypted`  ~7:20
`test_up.sh encrypted` ~9:00
`test_ds.sh` is half a second.

So, without building most of the time is indeed spent in `test_up.sh`.
I'm going to dig out the numbers for what github does for us now.

**Comment by leftwo** [comment]
For github's numbers:
Start: 21:24:41
Setup: 4 sec
toolchain: 21:24:44 -> 21:25:09
clone: 21:25:09 -> 21:25:11
build: 21:25:11 -> 21:30:08
`test_up.sh unencrypted`: 21:30:28 -> 21:40:35    ptime says 6:47 for "real"
`test_up.sh encrypted`: 21:40:35 -> 21:50:49   ptime says 6:20 for "real"
fin: 21:50:49

So, it is roughly 5 min for setup and compile, then 10 min each for `test_up.sh encrypted` then `test_up.sh unencrypted`

That is not a huge difference, but maybe a first pass at improvement can be looking at how to make sure test_up is only running tests it really has to (and if we need both encrypted and unencrypted)

**Comment by leftwo** [comment]
We made this a little better with various commits, and now it's not a big issue any longer, so closing this old issue.
