### ISSUE TITLE
client cli on illumos self destructs

### ISSUE THREAD

**Issue by leftwo** [oxidecomputer/crucible#258]
I run cliserver on atrium (over mosh+tmux).

First run:
```
./tools/downstairs-daemon.sh -u
```
Then in a second window:
```
cargo run -p crucible-client -- cli-server -t 127.0.0.1:8810 -t 127.0.0.1:8820 -t 127.0.0.1:8830 
```

Then run the cli "client" in a third window:
```
cargo run -p crucible-client -- cli
```
WhenI connect the cli client, it closes my tmux window, then closes my mosh connection.
The same is not true when I run through tmux on the mac.

If I ssh to atrium and run the client cli, it just hangs.  
Figure out why the cli does this, what is special about either atrium or illumos.

**Comment by rmustacc** [comment]
Does the same thing happen if you use ssh and/or do not use tmux?

**Comment by leftwo** [comment]
> 

No, in that case I can see the client cli connect to the server, but it just hangs and no output appears on the cli side.  It's possibly something with the crate I'm using for the command line management.

**Comment by leftwo** [comment]
The issue appears to be in the rustyline crate.  I can reproduce it using just their example code from
https://crates.io/crates/rustyline

**Comment by rmustacc** [comment]
OK, that's interesting and good to know. While I could make some wild guesses this is where our resident terminal whisperer @jclulow maybe can help.

**Comment by leftwo** [comment]
His `tmux` `terminal` keyword match nerd snipe has already been activated and he is messaging me from the dentist chair OOB

**Comment by leftwo** [comment]
truss from running the example rustyline program just over an SSH session. 
Here I am running truss on atrium after ssh'ing into it, and sending truss output to a file

```
alan@atrium:rlt$ truss -o /tmp/rlt-out ./target/debug/rlt
Hello, world!
Here we go
```

At this point the output stops and I see no more.  Looking at the truss output, I can see
things continue and the program is accepting my commands and acting on them:

```
(snip early truss output)
write(1, " H e r e   w e   g o\n", 11)          = 11
ioctl(0, TCGETS, 0xFFFFFC7FFFDFCC58)            = 0
open("/dev/urandom", O_RDONLY|O_CLOEXEC)        = 3
read(3, "1CCF D aC6 ]DCAF X86DE )".., 16)       = 16
close(3)                                        = 0
ioctl(0, TCSETSW, 0xFFFFFC7FFFDFCFA8)           = 0
write(1, "1B [ ? 2 0 0 4 h", 8)                 = 8
ioctl(1, TIOCGWINSZ, 0xFFFFFC7FFFDFC140)        = 0
brk(0x012CD000)                                 = 0
write(1, "\r1B [ 0 K > >  \r1B [ 3".., 13)      = 13
read(0, 0xFFFFFC7FFFDFC5E4, 1)  (sleeping...)
read(0, " a", 1)                                = 1
write(1, " a", 1)                               = 1
read(0, " l", 1)                                = 1
write(1, " l", 1)                               = 1
read(0, " a", 1)                                = 1
write(1, " a", 1)                               = 1
read(0, " n", 1)                                = 1
write(1, " n", 1)                               = 1
read(0, "\r", 1)                                = 1
ioctl(0, TCSETSW, 0xFFFFFC7FFFDFD478)           = 0
write(1, "1B [ ? 2 0 0 4 l", 8)                 = 8
write(1, "\n", 1)                               = 1
write(1, " L i n e :   a l a n\n", 11)          = 11
(snip more output)
```

So, it looks like the program is running, but I'm no longer able to see output.

**Comment by leftwo** [comment]
If I connect to illumos with mosh (and no tmux) then running the example will cause the mosh session to self destruct and close the connection.

If I run on /dev/console on my illumos machine, the example program works as expected.

**Comment by leftwo** [comment]
I "fixed" this by moving to reedline in https://github.com/oxidecomputer/crucible/pull/263
So, I'm going to close this issue.
