### ISSUE TITLE
figure out how to version crucible

### ISSUE THREAD

**Issue by jmpesp** [oxidecomputer/crucible#307]
Before shipping, we'll want to figure out how to version at least the following:

- the wire protocol
- the on-disk format
- the db tables and schema
- the encryption

This issue tracks that work.

**Comment by leftwo** [comment]
Wire protocol (at least part one) is done with this: https://github.com/oxidecomputer/crucible/pull/705#pullrequestreview-1400323202

**Comment by leftwo** [comment]
I think enough of this is now in (on disk version is now in as well), that we can close this issue.
