### ISSUE TITLE
Activation and volume construction

### ISSUE THREAD

**Issue by leftwo** [oxidecomputer/crucible#440]
We may have a chicken/egg issue around activation and volume creation.

During volume creation in propolis. 
We _create() a CrucibleBackend.  To do this, we take the VolumeConstructionRequest and:

```
let volume = Arc::new(tokio::task::block_in_place(|| {
            Volume::construct(request, producer_registry)
        })?);
```

Then, 
```
        volume.activate(gen)?;
```

Afterwards, we call `volume.get_block_size()?` and `volume.total_size()?` which require activation.

However, for migration, we can't `volume.activate` until we are ready to takeover from the other side.

So, possibly, we either need to be able to return some info about the volume before it is activated, or move
things in the CrucibleBackend until after activation, if possible.

**Comment by leftwo** [comment]
Possibly, we can return block size and total_size as soon as we get one downstairs to answer even if we have not activated.  The idea being that if the three DS don't match, we are going to fail the activate anyway, and so the early info about block size and volume size, if wrong, won't matter as we will have failed the activation.

**Comment by gjcolombo** [comment]
I've been poking around at this a little bit and have a (probably naive) question:

> Afterwards, we call volume.get_block_size()? and volume.total_size()? which require activation.

Do these technically require activation, or is that just an accident of the way the upstairs/downstairs negotiation currently works?

IIUC when serving a region a downstairs learns the block size and extent count before it ever starts serving requests from an upstairs (the region data is read in `build_downstairs_for_region`, which precedes downstairs `main`'s call to `start_downstairs`). If these aren't mutable while the downstairs is running (they don't seem like they should be, but are they?) then it seems like an upstairs could obtain them before ever activating, either by reworking the upstairs/downstairs negotiation protocol or by letting the upstairs query region information ad hoc.

I can try this out if this sounds promising, but wanted to ask first in case I'm missing something. We can make LM work on the Propolis side without doing any of this, but it requires a fair bit of refactoring and I want to see if other approaches will come out cleaner.

**Comment by gjcolombo** [comment]
Thanks! Seems like we're thinking along the same lines here. Just to check my understanding, though, what I'm hearing/reading is that we really ought to be able to get all the `RegionDefinition` information for a volume's regions in two ways:

1. Nexus should know all of it because it was the entity that created all the regions in the first place; therefore, it could specify all this information to Propolis in a disk's `VolumeConstructionRequest`. (Actually, I think the VCR already unconditionally includes a block size today, but it has no extent/total size information.)
2. Upstairs ought in principle to be able to fetch this information from at least one (or all three) Downstairs prior to activating, but today it can't for assorted reasons (e.g. `Guest` will reject `BlockOp::QueryBlockSize` and `QueryTotalSize` if the upstairs isn't active; the only code path that tries to obtain a `RegionDefinition` is the upstairs/downstairs negotiation path that necessarily involves activation). Also, even if Upstairs does get this information at some other time, the Crucible backend needs some way to wait for it to become available (currently it just activates and `await`s that, and that's sufficient, but now we don't want to activate anymore).

Either of these fixes alone would solve the "CrucibleBackend needs to know the block/total sizes when it gets created, and it can't activate at that time" problem, but ideally we'd have both, and the backend would cross-check what Downstairs sends with what Nexus sent.

Is that a fair summary?

**Comment by leftwo** [comment]
> Thanks! Seems like we're thinking along the same lines here. Just to check my understanding, though, what I'm hearing/reading is that we really ought to be able to get all the `RegionDefinition` information for a volume's regions in two ways:
> 
> 1. Nexus should know all of it because it was the entity that created all the regions in the first place; therefore, it could specify all this information to Propolis in a disk's `VolumeConstructionRequest`. (If we're being really pedantic, I think the VCR already unconditionally includes a block size today, but it has no extent/total size information.)

Yes.  And really Nexus should be telling Propolis all this, [we just never plumbed it in](https://github.com/oxidecomputer/crucible/blob/d19e92f7f204b22477ace60e98fc1163d50e28e1/upstairs/src/lib.rs#L5631).
(And, to be clear here, It's not that Nexus is bad, it's just that we never wrote the code over in Nexus to do it)

> 2. Upstairs ought in principle to be able to fetch this information from at least one (or all three) Downstairs prior to activating, but today it can't for assorted reasons (e.g. `Guest` will reject `BlockOp::QueryBlockSize` and `QueryTotalSize` if the upstairs isn't active; the only code path that tries to obtain a `RegionDefinition` is the upstairs/downstairs negotiation path that necessarily involves activation). Also, even if Upstairs does get this information at some other time, the Crucible backend needs some way to wait for it to become available (currently it just activates and `await`s that, and that's sufficient, but now we don't want to activate anymore).

Yes, this is also true that we could request `RegionDefinition` before activation from each downstairs.
 
> Either of these fixes alone would solve the "CrucibleBackend needs to know the block/total sizes when it gets created, and it can't activate at that time" problem, but ideally we'd have both, and the backend would cross-check what Downstairs sends with what Nexus sent.
> 
> Is that a fair summary?

Having just your number 2 above, I don't think would solve our problem as it would just be a race between the guest sending a `QueryBlockSize` and at least one upstairs task asking for and getting back the `RegionDefinition` from a downstairs.  I do agree that the Upstairs should still ask (and then verify) a downstair's RD is what it thinks it should be.

**Comment by gjcolombo** [comment]
> Having just your number 2 above, I don't think would solve our problem as it would just be a race between the guest sending a QueryBlockSize and at least one upstairs task asking for and getting back the RegionDefinition from a downstairs.

Agreed, we would still need some kind of synchronization point so that the `QueryBlockSize` request can actually be satisfied when it's issued. (We just don't want that to be activation.)

> (Did I mention we would love help on this?)

I'd be happy to give some of this a try. I'll spend some time on it this week and see how far I can get.

**Comment by leftwo** [comment]
> Agreed, we would still need some kind of synchronization point so that the `QueryBlockSize` request can actually be satisfied when it's issued. (We just don't want that to be activation.)

I think if we pass the upstairs the `RegionDefinition` info on startup, then we could change `QueryBlockSize` to just read the passed in info.  The reconcile process (that happens at activation) could be the place where synchronization happens and if what the Upstairs started with does not match what the Downstairs tells the upstairs, then the activation should fail.  That 2nd step could even be work that comes later, as getting migration unblocked seems like a good first step.
 
> > (Did I mention we would love help on this?)
> 
> I'd be happy to give some of this a try. I'll spend some time on it this week and see how far I can get.
❤️
