### ISSUE TITLE
add some tests in `downstairs/src/region.rs` for larger contiguous and non-contiguous reads and writes

### ISSUE THREAD

**Issue by faithanalog** [oxidecomputer/crucible#446]
see https://github.com/oxidecomputer/crucible/pull/444#pullrequestreview-1111201668

We're adding in some logic to do different behavior for reads/writes with contiguous block ranges, so we should add some tests for

- read() with a single large contiguous range of requests
- read() with multiple disjoint contiguous ranges of requests
- read() with multiple requests, none of which are contiguous

- write() with a single large contiguous range of requests
- write() with multiple disjoint contiguous ranges of requests
- write() with multiple requests, none of which are contiguous

- duplicates of the write tests mentioned above, but with `only_write_unwritten` set to true instead of false

**Comment by faithanalog** [comment]
I'm happy to do this now so we don't forget about it. We'll also have some coverage of this from any integration tests doing larger reads/writes, but it may not be complete over the entire range of possible valid inputs

**Comment by jmpesp** [comment]
addressed in https://github.com/oxidecomputer/crucible/pull/650
