### ISSUE TITLE
Does Guest need the active field?

### ISSUE THREAD

**Issue by jmpesp** [oxidecomputer/crucible#461]
The Guest has its own idea of being active:

```rust
    pub async fn is_active(&self) -> bool {
        // A Guest is active if it's seen the Upstairs return that it's active
        let active = self.active.lock().await;
        *active
    }
```

Does it need this? What if the Guest idea of active and the Upstairs / BlockIO idea of active go out of sync?

**Comment by leftwo** [comment]
I do not think the guest needs it.
The guest should just pass the request down to the upstairs where it has the most up to date information.

I figured we would rip it out when we do the proper generation number support, but no reason this piece can't 
be fixed independently.
