### ISSUE TITLE
Don't print the key in the logs

### ISSUE THREAD

**Issue by leftwo** [oxidecomputer/crucible#486]
We should not print the encryption key in the logs:

```
Oct 14 01:44:40.676 INFO Creating Crucible disk from request Volume { id: 1c84b66a-2282-4a90-993b-a2dbd1e9a000, block_size: 512, sub_volumes: [Region { block_size: 512, opts: CrucibleOpts { id: 1c84b66a-2282-4a90-993b-a2dbd1e9a000, target: [[fd00:1122:3344:101::b]:19000, [fd00:1122:3344:101::a]:19000, [fd00:1122:3344:101::7]:19000], lossy: false, flush_timeout: None, key: Some("Yj9fL9Za4xmiZkTydYdm5xqOPn4aPSPk+AfSGAG/qvM="), cert_pem: None, key_pem: None, root_cert_pem: None, control: None, read_only: false }, gen: 0 }], read_only_parent: Some(Url { id: 4bd0d3fa-0516-4967-af88-b644eb9ca950, block_size: 512, url: "http://[fd00:1122:3344:101::1]:54321/media/cloud/focal-server-cloudimg-amd64.raw" }) }
```

**Comment by jclulow** [comment]
Perhaps we should have a newtype for holding it that has Display and Debug implementations that just say something opaque like `[encryption key]`, to avoid any such accidents in future?

**Comment by andrewjstone** [comment]
Keys should also be wrapped with [zeroize](https://docs.rs/zeroize/latest/zeroize/) if they aren't already. You may want to use [secrecy](https://docs.rs/secrecy/latest/secrecy/) instead, which al

**Comment by jclulow** [comment]
> Keys should also be wrapped with [zeroize](https://docs.rs/zeroize/latest/zeroize/) if they aren't already. You may want to use [secrecy](https://docs.rs/secrecy/latest/secrecy/) instead, which also prevents debug logging. I haven't used it myself but came across it reading some code the other day.

We should figure out how to circulate that guidance more broadly I suspect?

**Comment by leftwo** [comment]
> > Keys should also be wrapped with [zeroize](https://docs.rs/zeroize/latest/zeroize/) if they aren't already. You may want to use [secrecy](https://docs.rs/secrecy/latest/secrecy/) instead, which also prevents debug logging. I haven't used it myself but came across it reading some code the other day.
> 
> We should figure out how to circulate that guidance more broadly I suspect?

CP huddle issue created!

**Comment by jmpesp** [comment]
It may be possible that we don't even need to store the key Upstairs, just accept it during `new` and use it to make the `EncryptionContext`?

**Comment by leftwo** [comment]
New code in propolis and crucible is in place and we no longer print the VCR.
