### ISSUE TITLE
guest gets an `Option<Logger>`

### ISSUE THREAD

**Issue by leftwo** [oxidecomputer/crucible#496]
Add a `Option<Logger>` field to the guest.  This will allow for logging on guest specific actions (like activation) where we don't have any other way to get logging info.

**Comment by jclulow** [comment]
Is `Option<Logger>` particularly ergonomic?  I have found myself creating a discard-only logger to pass around, as you can then just pass it to `info!(log, ...)` etc without conditionals; i.e.,

```rust
pub fn discard_logger(&self) -> slog::Logger {
    slog::Logger::root(slog::Discard, slog::o!())
}
```

**Comment by leftwo** [comment]
I don't like the ergonomics of the `Opt<Log>`, and. hhm..  

I started writing why your idea would not work, but actually I think it might.
On creation of the `Guest`, if a logger is not provided then we do as you suggest and create one, assuming that if the creator of the guest could not be bothered to pass one in, then they don't care about logging.

**Comment by jclulow** [comment]
It is conceivable in the limit that we could come up with a discard-like logger that doesn't print anywhere but still makes DTrace probe firings too, so that you could get the log messages out at runtime even if the containing program is not into it.

**Comment by leftwo** [comment]
After many refactors, we now have a logger available to the new guest layer
