### ISSUE TITLE
Guest boot time regression starting at commit 29b6ac2

### ISSUE THREAD

**Issue by gjcolombo** [oxidecomputer/crucible#529]
I'm seeing a boot time regression in PHD-launched Debian 11 no-cloud VMs starting with Crucible commit 29b6ac2. The PHD test that's displaying this creates three 10 GiB Crucible regions, launches three Crucible downstairs processes for them, and launches a VM that attaches to those regions, using a Debian 11 no-cloud image on the local filesystem as a read-only parent volume. The problem doesn't repro if I build and run Crucible at 22ffcda (updating Propolis's dependencies accordingly but leaving everything else in Propolis the same).

Here are sample boot times from four different configurations, measured from the time PHD logs the first dmesg line from the guest OS to the time it logs the guest login prompt:

| Crucible commit | Build flavor | Boot time |
|---|---|---|
|22ffcda|release|32.27 seconds|
|22ffcda|debug|35.44 seconds|
|29b6ac2|release|43.34 seconds|
|29b6ac2|debug|170.83 seconds|

There seems to be moderately high variance in these runtimes--in most of my runs with debug 29b6ac2 before this, the guest actually fails to boot in 180 seconds and enters emergency mode, causing the test to time out (since it never gets a login prompt).

The PHD framework code to support Crucible disks is new, and it's possible that it's configuring something suboptimally, but AFAICT I have PHD using the same general configuration (and specifically extent sizes) that Omicron does. The diff containing the new framework code is here: https://github.com/gjcolombo/propolis/compare/bc6ee45..2407ad5. The chosen extent size is (supposed to be) 64 MiB to match https://github.com/oxidecomputer/omicron/blob/f47bbfd1d20f10ef6287d62a06b8a2a00a912d6b/nexus/src/db/datastore/region.rs#L97.

---

The framework code needed to repro and the Debian 11 guest image configuration are not in Propolis mainline yet, so the repro steps are as follows:

1. Check out Crucible at the commit of interest & build in either the debug or release configuration
2. Obtain a Debian 11 no-cloud image from https://cloud.debian.org/images/cloud/bullseye/latest/
3. Check out https://github.com/gjcolombo/propolis/tree/gjcolombo/phd-crucible (**N.B.**: this requires Rust 1.64 to build)
4. In this clone, make a copy of `phd-tests/artifacts.toml` and add an entry similar to the following:

```
[guest_images.debian11] 
guest_os_kind = "debian11nocloud" 
metadata.relative_local_path = "debian-11-nocloud-amd64.raw"
metadata.expected_digest = "429b73e2b8b6c2bcd03fdc213d0c0b174252b2e3addf7958848020989f2d638e" 
```

where the `expected_digest` is the SHA256 checksum of the image.

5. Change the workspace Cargo.toml's Crucible references to the commit from step 1
6. `cargo build -p propolis-server`
7. `cargo build -p phd-runner --profile=phd`
8. Create a temp directory for PHD files: `mkdir /tmp/phd`
9. Run the test:

```
pfexec /path/to/propolis/target/phd/phd-runner run \
--propolis-server-cmd /path/to/propolis/target/debug/propolis-server \
--artifact-toml-path /path/to/artifacts_from_step_4.toml \
--artifact-directory /path/to/dir/with/debian/image \
--tmp-directory /tmp/phd \
--default-guest-artifact debian11 \
--crucible-downstairs-cmd /path/to/crucible/target/$FLAVOR/crucible-downstairs \
--include-filter crucible::smoke::boot_test
```

The test will generally pass unless boot takes too long and causes the guest to go into emergency mode. The test harness logs all guest serial console output, which can be used to measure the time from first kernel log line to the login prompt.

**Comment by leftwo** [comment]
I have also noticed a change in performance with [29b6ac](https://github.com/oxidecomputer/crucible/commit/29b6ac28205fbdd3331aae7ddc2ff16640fca37f) 
See [issue 519](https://github.com/oxidecomputer/crucible/issues/519)

We can demonstrate a difference in performance when going to 29b6ac using just 
crucible performance tools, so I'm pretty sure that at least some (if not all) of the change in 
performance reported here is due to the changes in 29b6ac and unrelated to any PHD 
configuration.  I am surprised though by how much the debug build changed things, that
is almost a 5x difference!
 
The changes in 29b6ac are needed for correctness.  We have not yet looked
at those changes to determine if a better way to achieve the same solution exists without 
as large of an impact on performance.

**Comment by leftwo** [comment]
> ... creates three 10 GiB Crucible regions

Could you share the block size, extent size, and extent count used to create the regions?
Also, are you using encryption or not?

Do all three regions reside on the same physical machine and the same disk?
(Most of our CI tests do this, but it's good to know exactly what setup was used here).

**Comment by gjcolombo** [comment]
Oops, I missed #519--should've looked more closely before filing! Mea culpa.

> Could you share the block size, extent size, and extent count used to create the regions? Also, are you using encryption or not?

Sure, here are the command lines to the crucible-downstairs processes (should be 64 MiB extents with no encryption if I've done all my math correctly):

```
2022-11-19T00:54:28.936097Z  INFO phd_framework::disk::crucible: 283: Running crucible-downstairs args=["create", "--block-size", "512", "--data", "/home/greg/phd_data/736bc0f3-6365-4033-b719-4cae061bbf37_9000", "--encrypted", "false", "--uuid", "736bc0f3-6365-4033-b719-4
cae061bbf37", "--extent-size", "131072", "--extent-count", "160"]                
                                                                                                                                                                                               
2022-11-19T00:54:29.152940Z  INFO phd_framework::disk::crucible: 160: Created Crucible region using crucible-downstairs stdout="" stderr="Nov 19 00:54:28.964 INFO Created new region file \"/home/greg/phd_data/736bc0f3-6365-4033-b719-4cae061bbf37_9000/region.json\"\nNov 19
 00:54:29.116 INFO UUID: 736bc0f3-6365-4033-b719-4cae061bbf37\nNov 19 00:54:29.117 INFO Blocks per extent:131072 Total Extents: 160\n" status=ExitStatus(unix_wait_status(0))
```

> Do all three regions reside on the same physical machine and the same disk?

Yes, all three on the same physical machine and M.2 disk (it's one of my home machines and not an Oxide lab machine; I can dig up the specs if needed).

**Comment by leftwo** [comment]
PR #576 solved the perf problems introduced here.
(Or at least it should have, as it solved others of a similar nature)
If not, please let me know!
