### ISSUE TITLE
Read after flush means hash mismatch

### ISSUE THREAD

**Issue by leftwo** [oxidecomputer/crucible#595]
Running the test_repair.sh script, I encountered this panic on hash mismatch:
```
02/30 Write block 385  len 32768  data:179  14 234 182 247 205 165  93 
03/30 Read  block  28  len 32768
04/30 Read  block 459  len 16384
05/30 Write block 172  len 40960  data:135 230 223 200 244  30 254 210 102  80 
06/30 Read  block 192  len 32768
07/30 Read  block  91  len 12288
08/30 Flush
09/30 Write block  85  len 32768  data:133 142 217 174 187 157 110 100 
10/30 Read  block 310  len 36864
11/30 Flush
12/30 Write block 171  len  8192  data:165 136 
thread 'tokio-runtime-worker' panicked at '[0] read hash mismatch on id 1006
Expected [Some(fc14853c232d8295), Some(9845e4de2549c015), Some(9aee68ebcf51cfb)]
Computed [Some(f1f24e1091a86eac), Some(f55039b4811a7962), Some(9aee68ebcf51cfb)]
guest_id:7 request:[ReadRequest { eid: 4, offset: Block { value: 11, shift: 12 } }, ReadRequest { eid: 4, offset: Block { value: 12, shift: 12 } }, ReadRequest { eid: 4, offset: Block { value: 13, shift: 12 } }]
job state:{1: Done, 0: Done, 2: Done}', upstairs/src/lib.rs:3265:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Exit on repair fail, loop: 53575, choice: 0
```

I suspect what happened is the following:

I've taken the output from the test and replaced the job number/total jobs with the downstairs side job ID.
Job IDs always start with 1001 and (just discovered as I'm writing this) there is a bug in crutest where it
does not print anything for the first job.
```
    ID    IO  BLOCK  SIZE  DATA WRITTEN (If a write)
  1001  Write   385 32768  179  14 234 182 247 205 165  93
  1002   Read    28 32768
  1003   Read   459 16384
  1004  Write   172 40960  135 230 223 200 244  30 254 210 102  80
  1005   Read   192 32768
  1006   Read    91 12288
  1007  Flush
  1008  Write    85 32768  133 142 217 174 187 157 110 100
```
For this analysis, we can ignore jobs before 1006.
At 1006, A Read of block 91 went out,
One downstairs (not 0) responded (which records the hash of the read result) ack send to the guest.
At 1007 A flush was issued, at least 2 downstairs ack'd.
At 1008 A write was issued to block 85 of length 8 (so also covering block 91).
The write, job 1007 finished on at least downstairs 0.
Downstairs 0 now handles the read request at 1006, but the write for 1008 has already
been serviced, this read now returns different data than the first read did, and we get our panic.

So, I think there may be a dependency issue with allowing a read issued before a flush then write
to be serviced both before and after that flush then write.

If I check block 91 now, all three downstairs agree on what it has, which does fit within
this analysis.

**Comment by jmpesp** [comment]
> So, I think there may be a dependency issue

I think you're right!

Currently:
- [flushes depend on](https://github.com/oxidecomputer/crucible/blob/0bf7c2794b0fecaa9580ed9d91d2c11c7f1b8f85/upstairs/src/lib.rs#L4916-L4925):
    - the last flush
    - all writes seen since the last flush
- [writes depend on](https://github.com/oxidecomputer/crucible/blob/0bf7c2794b0fecaa9580ed9d91d2c11c7f1b8f85/upstairs/src/lib.rs#L5093-L5104):
    - the last flush
    - any job with overlapping impacted blocks since the last flush
- [reads depend on](https://github.com/oxidecomputer/crucible/blob/0bf7c2794b0fecaa9580ed9d91d2c11c7f1b8f85/upstairs/src/lib.rs#L5291-L5297):
    - any write job with overlapping impacted blocks

When searching backwards for jobs to depend on when assigning deps for new flush and write jobs, the loop will terminate when it reaches a flush. This is *not* true for reads.

Taking the jobs here:

```
    ID    IO  BLOCK  SIZE
  1001  Write   385 32768
  1002   Read    28 32768
  1003   Read   459 16384
  1004  Write   172 40960
  1005   Read   192 32768
  1006   Read    91 12288
  1007  Flush
  1008  Write    85 32768
```

For there to be a dependency issue:
- job 1008 would not depend on job 1006 finishing
    - this is true because the flush acts as a barrier when searching for write dependencies
- job 1007 would not depend on job 1006 finishing
    - this is true because flushes don't currently depend on reads

The following unit test proves this:

```rust
    #[tokio::test]
    async fn test_read_flush_write_hash_mismatch() {
        // Test that the following job dependency graph is made:
        //
        //     |      block     |
        // op# | 95 96 97 98 99 | deps
        // ----|----------------|-----
        //   0 |  R  R          |
        //   1 | FFFFFFFFFFFFFFF|
        //   2 |     W  W       | 1

        let upstairs = make_upstairs();
        let (ds_done_tx, _ds_done_rx) = mpsc::channel(500);
        upstairs.set_active().await.unwrap();

        // op 0
        upstairs
            .submit_read(
                Block::new_512(95),
                Buffer::new(512 * 2),
                None,
                ds_done_tx.clone(),
            )
            .await
            .unwrap();

        // op 1
        upstairs
            .submit_flush(
                None, None, ds_done_tx.clone(),
            )
            .await
            .unwrap();

        // op 2
        upstairs
            .submit_write(
                Block::new_512(96),
                Bytes::from(vec![0xff; 512 * 2]),
                None,
                false,
                ds_done_tx.clone(),
            )
            .await
            .unwrap();

        let ds = upstairs.downstairs.lock().await;
        let keys: Vec<&u64> = ds.ds_active.keys().sorted().collect();
        let jobs: Vec<&DownstairsIO> =
            keys.iter().map(|k| ds.ds_active.get(k).unwrap()).collect();
        assert_eq!(jobs.len(), 3);

        // assert read has no deps
        assert!(jobs[0].work.deps().is_empty()); // op 0

        // assert flush has no deps
        assert!(jobs[1].work.deps().is_empty()); // op 0

        // assert write depends on flush
        assert_eq!(jobs[2].work.deps(), &[jobs[1].ds_id]);
    }
```

For this to not be a dependency issue, writes have to depend on all in-flight jobs that have overlapping blocks, not just jobs since the last flush.
