### ISSUE TITLE
Determine how much storage to "reserve" for overhead

### ISSUE THREAD

**Issue by leftwo** [oxidecomputer/crucible#605]
Figure out how much physical storage crucible needs for overhead to avoid filling up 100% of space on the disk.

**Comment by askfongjojo** [comment]
Per storage huddle, the minimum for FCS is to set a reasonable quota.

**Comment by leftwo** [comment]
I think we can do a first pass at this with both a quota and a reservation when we create
the dataset for a region.

I'm not sure yet how snapshots will factor into this, as a snapshot might require a 2x reservation
while the snapshot exists. 
Also TBD, if we have multiple snapshots, how much do we need to reserve for those?

**Comment by leftwo** [comment]
The fix for this has been merged to main in the crucible repo.
Propolis PR is out,
once that PR is merged, then Omicron will need to get a new pointer to latest crucible.

**Comment by leftwo** [comment]
This has landed in Omicron.
