### ISSUE TITLE
Add dependabot

### ISSUE THREAD

**Issue by leftwo** [oxidecomputer/crucible#70]
Get dependabot or some other automated way of updating dependencies working.

**Comment by leftwo** [comment]
> Hi, can I work on this issue?

Hi Aditi, 
Thanks for your interest.  Let me go figure out if:
1: We really are ready to make this change now (we are still in active prototyping stages).
2: We are ready to accept changes to this repo from outside Oxide.

 If both are true, then I'll swing back and see if you are still interested and what would be the next steps.
Thanks,
-Alan

**Comment by aditirao7** [comment]
Alright, thank you :)

**Comment by leftwo** [comment]
> Alright, thank you :)



> Hi, can I work on this issue?

Hi Aditi,
At this time, we are not ready to take outside contributions to the crucible repo, though I really do appreciate you reaching out and offering to do the work.

-Alan

**Comment by aditirao7** [comment]
@leftwo Oh okay, I understand. Thank you for your prompt response 😃

**Comment by leftwo** [comment]
Trying renovate, and will revisit this if that does not work.
