### ISSUE TITLE
crucible agent failed to start a downstairs

### ISSUE THREAD

**Issue by leftwo** [oxidecomputer/crucible#704]
On rack2 (dogfood) we uploaded an image, then created an instance based on this image.

Something happened in the crucible agent for one of the downstairs and it failed to start that downstairs.
propolis server was stuck waiting for the third downstairs.

**Comment by leftwo** [comment]
Sled agent log:
[sled-agent-log-when-agent-failed.log](https://github.com/oxidecomputer/crucible/files/11299614/sled-agent-log-when-agent-failed.log)

**Comment by leftwo** [comment]
nexus log (too big to attach) is here: /net/catacomb/data/staff/core/rack2/BRM42220070/crucible-704

**Comment by jmpesp** [comment]
We saw Nexus successfully tell the agent to start three Downstiars for a snapshot:

```json
{
  "msg": "crucible running snapshot RunningSnapshot { id: RegionId(\"5dfcd3b5-fec0-4d3b-a383-121fa6a5e916\"), name: \"d83d29ce-b16f-45bd-848a-bbae5b002693\", port_number: 19001, state: Created }",
  "v": 0,
  "name": "74403a62-fffd-45bb-aeb7-de0af88df320",
  "level": 30,
  "time": "2023-04-21T13:46:21.074502015-07:00",
  "hostname": "oxz_nexus",
  "pid": 16238,
  "saga_id": "aba0627b-b11e-43ee-821a-2ef8ccd216c0",
  "saga_name": "finalize-disk",
  "component": "ServerContext"
}
{
  "msg": "crucible running snapshot RunningSnapshot { id: RegionId(\"68cb66a7-7a9f-4c9e-95f9-9617f27289b0\"), name: \"d83d29ce-b16f-45bd-848a-bbae5b002693\", port_number: 19001, state: Created }",
  "v": 0,
  "name": "74403a62-fffd-45bb-aeb7-de0af88df320",
  "level": 30,
  "time": "2023-04-21T13:46:21.136658265-07:00",
  "hostname": "oxz_nexus",
  "pid": 16238,
  "saga_id": "aba0627b-b11e-43ee-821a-2ef8ccd216c0",
  "saga_name": "finalize-disk",
  "component": "ServerContext"
}
{
  "msg": "crucible running snapshot RunningSnapshot { id: RegionId(\"6bbc4067-b739-47ee-9472-d336a7f5c286\"), name: \"d83d29ce-b16f-45bd-848a-bbae5b002693\", port_number: 19001, state: Created }",
  "v": 0,
  "name": "74403a62-fffd-45bb-aeb7-de0af88df320",
  "level": 30,
  "time": "2023-04-21T13:46:21.198667256-07:00",
  "hostname": "oxz_nexus",
  "pid": 16238,
  "saga_id": "aba0627b-b11e-43ee-821a-2ef8ccd216c0",
  "saga_name": "finalize-disk",
  "component": "ServerContext"
}
```

We saw each respective crucible agent record in `/data/crucible.json` that a running snapshot had been requested, but only two of those actually spun up the read-only downstairs. When the third agent was bounced with svcadm, it read crucible.json and brought up the missing read-only downstairs.

Something got stuck in the agent - it received (and enqueued) the "running snapshot" request but didn't carry it out.
