### ISSUE TITLE
Guest read/write workload can use disk I/O performance improvement

### ISSUE THREAD

**Issue by askfongjojo** [oxidecomputer/crucible#858]
A customer benchmarked their workloads with heavy database read/write (PostgreSQL and SQLite) that currently run on ESX vs Oxide. They have observed 50% slower I/O on Oxide.

The ESX VM is backed by an iSCSI connection to a NAS storage pool (ZFS array of spinners). The traffic is intra-VLAN and no routing is involved.

**Comment by leftwo** [comment]
Some specific questions to ask that might help us narrow the performance focus:

Crucible is encrypting data in flight and at rest, is this true for the comparison?
What is the workload read write mix?
What block size is the workload using, 4096?
What is the IO depth (outstanding IOs at a time) for the workload?

I believe the volume under test is 128GB with a 4K block size, and attached to a 32CPU 64GB RAM VM.

**Comment by askfongjojo** [comment]
Sure, I'll follow up with the customer to better characterize their workload (I'd also ask how many threads they used for their database r/w job).

**Comment by askfongjojo** [comment]
Here are the questions I sent to INL and responses from them:

Questions:
1. Is data encryption (in transit and at rest) involved in the ESX/NAS storage?
2. Is the read/write mix of the reference workload also 75%:25%, similar to the FIO test?
3. Do you happen to know the write block size and IO depth of the reference workload?
4. Finally, what is the number of threads used for reads and writes?

Answers:
1. Our existing ESX infrastructure consists of 2x 40Gb NICs that carries all traffic for our network (user VLANS + storage VLANs). The ESX hosts attach in the same storage VLAN as the NAS they communicate with over iSCSI. That NAS has an identical 40Gb NIC setup.
2. Our initial reference workload is probably closer to 75% write / 25% read ratio to initialize the system with a bulk upload -> batch processing workload. Individual worker processes are quite CPU/RAM intensive before relaying their results back to a Minio object store and a PostgreSQL database. I would need to do more detailed profiling of this specific workload, but we were observing visually obvious latency on container start-up.
3. I know both file systems and underlying block devices are 4k sized. The ESX VM was using LVM whereas the cloud image on Oxide was not. Not sure about the fully loaded IO depth on the system.
4. I don't have a specific number because our task orchestrator allocates worker processes based on measured memory pressure on the host OS. In general, we try to go as parallel as possible on this bulk processing phase. Each worker will be read/writing from an SQLite file before reporting results. Global results from those workers are collected by a central service that handles the SQL bulk inserts and some serialization to objects in Minio.

Hopefully this provides some useful context. This was a relatively basic test setup running a development build of our full distributed system on each host via Docker Compose. We could certainly schedule a less complex system to profile but this one is our most important migration target.

___
Garrett didn't include the encryption details in his written responses but in our weekly sync with them earlier, he mentioned that there was encryption on the zvol but there was no disk-level encryption. There are probably more details to that. @leftwo - Please add any other pertinent details based on what you heard in the same meeting.

**Comment by askfongjojo** [comment]
Want to capture what @pfmooney pointed out the other day:
____
I wanted to bring [this](https://github.com/oxidecomputer/propolis/blob/master/lib/propolis/src/block/crucible.rs#L187-L188) to attention - the fact that we're artificially limiting the number of requests in fight with the upstairs to 8 in propolis

**Comment by askfongjojo** [comment]
Closing this as a duplicate of #586
