### ISSUE TITLE
dispatch less flush tasks

### ISSUE THREAD

**Issue by faithanalog** [oxidecomputer/crucible#872]
we don't need to flush extents that aren't dirty. Right now we spawn one flush task for *every* extent during a flush command. We should be able to cut down on this a lot by keeping a set in the region struct of which extents actually need flushes. 

So what extents _do_ need flushes? Any of them that are marked dirty.

- when opening an extent, check if it is dirty, if so, add to the list. will get flushed during the first flush command received from upstairs
- when writing to an extent, add it to the list
- when flushing, issue flush jobs for everything on the list. clear the list

Question: what about if a flush fails? Well maybe we have bigger problems, and i think we failkill the downstairs at that point anyway.

**Comment by leftwo** [comment]
> Question: what about if a flush fails?

Yeah, that's bad news as we basically can't continue using that downstairs till we know what condition the data is in, and pulling it out of the region set and repair it is our only current path forward at the moment.
