### ISSUE TITLE
Generation number support

### ISSUE THREAD

**Issue by leftwo** [oxidecomputer/crucible#94]
Upstairs needs to have a generation (or attach) number it uses when connecting to
the downstairs.  That number should eventually come from nexus, but initially we
can supply it on the command line.

**Comment by leftwo** [comment]
Part 1 of this is out for review.
For part 2, we will send the number to the downstairs and act on it.

**Comment by jmpesp** [comment]
Part 2 merged in https://github.com/oxidecomputer/crucible/pull/119

**Comment by leftwo** [comment]
Upstairs has generation numbers now, but there is still the support needed on the Nexus side.
