### ISSUE TITLE
On startup, a non-repair can finish before a downstairs task arrives to repair

### ISSUE THREAD

**Issue by leftwo** [oxidecomputer/crucible#948]
It's possible (I believe) that the reconciliation task has no work to do, and 
can get to the end of reconciliation and mark a downstairs as `Active` before
that downstairs task has even arrived at `cmd_loop`.

Since `Active` is not a state `cmd_loop` expects to find a downstairs in, we can trigger
this panic:

```
                panic!(
                    "[{}] {} Downstairs in invalid state: {}",
                    up_coms.client_id, up.uuid, bad_state,
                );
```

**Comment by mkeeter** [comment]
This happens frequently enough in CI to be annoying, e.g.

https://buildomat.eng.oxide.computer/wg/0/artefact/01HB9GNPDNEHC67HQYE3ZKDBR6/jdafiwf3gPbHY5M43SQImUC0yjr7uOXA22twFIiVqM7ZAzUC/01HB9GP96XZSFFFH6WNJESYCSW/01HB9JJE219KABFF7JGCTAJSB3/test_up_out.txt

**Comment by leftwo** [comment]
With the re-write in https://github.com/oxidecomputer/crucible/pull/1058 the conditions no
longer exist for this issue to happen.
