### ISSUE TITLE
Crucible should print out starting opts

### ISSUE THREAD

**Issue by leftwo** [oxidecomputer/crucible#971]
We don't print the VCR any longer in propolis, so crucible upstairs should
report, in a single easy to find log message, what it's opts are when starting.
Don't print the key value though, that should remain a secret.

**Comment by leftwo** [comment]
Ideally, we should also print session in each log line?
Or, improve on propolis side as to make it easier to tell the
difference between a ROP volume and the main volume.

**Comment by gjcolombo** [comment]
Related: oxidecomputer/propolis#536

**Comment by leftwo** [comment]
#973
